export * from './user'
export * from './class'
export * from './otp'
// export * from './classSchedule'
// export * from './parent'
export * from './school'
// export * from './student'
// export * from './subject'
// export * from './teacher'

