name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Lint and format admin service
        run: |
          npm run lint:admin
          npm run format:check:admin

      - name: Start admin service
        run: npm run start:admin

      - name: Lint and format user service
        run: |
          npm run lint:user
          npm run format:check:user

      - name: Start user service
        run: npm run start:user
